version: '2'
services:
  kibana:
    image: kibana:4
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  elasticsearch:
    image: elasticsearch:2
    ports:
      - "9200:9200"
      - "9300:9300"
